"""add clip table

Revision ID: 15b65feb5fc0
Revises: f1a2b3c4d5e6
Create Date: 2026-06-15 19:15:53.933047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from app_logger import ModuleLogger


# revision identifiers, used by Alembic.
revision: str = '15b65feb5fc0'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

logger = ModuleLogger("AlembicMigrations")


def upgrade() -> None:
    # Disable foreign keys temporarily for migrations
    op.execute("PRAGMA foreign_keys=OFF")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clip',
    sa.Column('clip_number', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('resolution', sa.Integer(), nullable=False),
    sa.Column('file_format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploader', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_exists', sa.Boolean(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_clip_media_id_media'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('clip_pkc'))
    )
    # ### end Alembic commands ###
    
    # Re-enable foreign keys after migrations
    op.execute("PRAGMA foreign_keys=ON")


def downgrade() -> None:
    # Disable foreign keys temporarily for migrations
    op.execute("PRAGMA foreign_keys=OFF")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clip')
    # ### end Alembic commands ###

    # Re-enable foreign keys after migrations
    op.execute("PRAGMA foreign_keys=ON")
